### ISSUE TITLE
Double quotes cutting off tooltips

### ISSUE THREAD

**Issue by cameronkagy** [dmc-uilabs/docent#24]
In the standalone version, go to the criteria page, expand the Materials thread. Hover over any of the instances of the word Material. The tooltip definition is cutoff at the double quotes when compared with the definition found on the definitions page.

**Comment by cameronkagy** [comment]
In DMC version, use the navigation page to go to Design->Producibility Program->10->"Are all modifications, upgrades, Diminishing Mfg Sources & Material Shortages (DMSMS), and other changes assessed for producibility?" Hovering over Material brings up only part of the definition in the tooltip (cuts off at a double quote)

**Comment by jmazrimas** [comment]
updated replace for proper HTML quot
