### ISSUE TITLE
DMC - start page date field

### ISSUE THREAD

**Issue by cameronkagy** [dmc-uilabs/docent#45]
In the DMC version using Firefox, the date field on the start page of the DMC version requires a date in format MM/DD/YYYY, but never tells the user the expected format.  User was trying to enter MM-DD-YYYY, and couldn't go any further.   There are no "/" symbols to guide the user.  Need to add expected format as a placeholder or in text as part of the label.

**Comment by jmazrimas** [comment]
added placeholder for mm/dd/yyyy -- verified working on chrome and ff
